# -*- coding: utf-8 -*-
"""Train_11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/MuhammadIrzam447/NewEncodings/blob/main/Train_11.ipynb

# New Section

Training Dataset
"""

import os
from collections import defaultdict
from datasets import Dataset
# import torch

train_image_file_paths = []
train_genre_labels = []
train_genre_labels_dict = {}

train_image_folder_add = "/Users/mmoscati/jku/LLaVA/mmimdb"
train_labels_file = "train_label.txt"

with open(train_labels_file, 'r') as file:
    for line in file:
        parts = line.strip().split('|')
        image_filename = parts[0].strip()
        item_id = image_filename.split('.')[0]

        labels = parts[1].strip().split(', ')  # Split labels by comma and remove leading/trailing spaces
        train_genre_labels.append(labels)
        # train_genre_labels_dict[item_id] = labels

label_counts = defaultdict(int)
for labels in train_genre_labels:
    for label in labels:
        label_counts[label] += 1

# Convert the defaultdict into a list of tuples
label_count_list = [(label, count) for label, count in label_counts.items()]

# Sort the list of tuples based on counts in descending order
sorted_label_count_list = sorted(label_count_list, key=lambda x: x[1], reverse=True)

# Display the sorted list
for label, count in sorted_label_count_list:
    print(f"{label}: {count}")

print("Total Labels: ", len(label_count_list))

min_label_count = 400
valid_labels = [label for label, count in label_counts.items() if count >= min_label_count]
valid_labels = sorted(list(valid_labels))

num_labels = len(valid_labels)
label2id = {label: str(i) for i, label in enumerate(valid_labels)}
id2label = {str(i): label for i, label in enumerate(valid_labels)}

train_multi_hot_labels = []

for labels in train_genre_labels:
    multi_hot = [1 if label in labels else 0 for label in valid_labels]
    train_multi_hot_labels.append(multi_hot)

"""Test Dataset"""


image_file_paths = []
genre_labels = []

image_folder_add = ""
labels_file = '/joint_test_label.txt'

with open(labels_file, 'r') as file:
    for line in file:
        parts = line.strip().split('|')
        filename = parts[0].strip()
        labels = parts[1].strip().split(', ')  # Split labels by comma and remove leading/trailing spaces
        image_path = os.path.join(image_folder_add, filename)
        image_file_paths.append(image_path)
        genre_labels.append(labels)

print(len(image_file_paths))
print(image_file_paths[0:10])

multi_hot_labels = []
for labels in genre_labels:
    multi_hot = [1 if label in labels else 0 for label in valid_labels]
    multi_hot_labels.append(multi_hot)

"""Creating Datasets"""

train_data = {'image': train_image_file_paths, 'label': train_multi_hot_labels}
ds_train = Dataset.from_dict(train_data)

val_data = {'image': image_file_paths, 'label': multi_hot_labels}
ds_val = Dataset.from_dict(val_data)

print(ds_train)
print(ds_val)

labels = valid_labels

"""Creating Model"""

#device = "cuda" if torch.cuda.is_available() else "cpu"
#print(device)


sample = train_dataset[0]

for item in train_dataset:
  print(item['pixel_values'].shape)
  print(item["labels"])
  break

"""
def collate_fn(batch):
  return {
      "pixel_values": torch.stack([x["pixel_values"] for x in batch]),
      "labels": torch.tensor([x["labels"] for x in batch]),
  }"""
